#XPath locators
home_header_menu = "/html/body/app-root/app-global-layout/div/div/app-header/header/div/div/div[1]/nav/a"
about_header_menu = "/html/body/app-root/app-global-layout/div/div/app-header/header/div/div/div[1]/nav/button[1]"
contacts_header_menu = "/html/body/app-root/app-global-layout/div/div/app-header/header/div/div/div[1]/nav/button[2]"
sign_up_button = "/html/body/app-root/app-global-layout/div/div/div/app-guest-layout/div/app-home/section/div/div/div[1]/div/button"
guest_log_in_link = "/html/body/app-root/app-global-layout/div/div/app-header/header/div/div/div[2]/button[1]"
sign_in_button = "/html/body/app-root/app-global-layout/div/div/app-header/header/div/div/div[2]/button[2]"
support_link = "//*[@id=\"contactsSection\"]/div/div/div[2]/a[2]"
add_car_button = "/html/body/app-root/app-global-layout/div/div/div/app-panel-layout/div/div/div/div[2]/div/app-garage/div/div[1]/button"
garage_header_menu = "/html/body/app-root/app-global-layout/div/div/app-header/header/div/div/div/nav/a[1]"
fuel_expenses_header_menu = "/html/body/app-root/app-global-layout/div/div/app-header/header/div/div/div/nav/a[2]"
instructions_header_menu = "/html/body/app-root/app-global-layout/div/div/app-header/header/div/div/div/nav/a[3]"
add_fuel_expense_button = "/html/body/app-root/app-global-layout/div/div/div/app-panel-layout/div/div/div/div[2]/div/app-fuel-expenses/div/div[1]/div/button"
close_add_car_popup_icon = "/html/body/ngb-modal-window/div/div/app-add-car-modal/div[1]/button/span"
select_brand_dropdown = "//*[@id=\"addCarBrand\"]"
select_model_dropdown = "//*[@id=\"addCarModel\"]"
mileage_input_field = "//*[@id=\"addCarMileage\"]"
add_car_pop_up_cancel_button = "/html/body/ngb-modal-window/div/div/app-add-car-modal/div[3]/button[1]"
add_car_pop_up_add_button = "/html/body/ngb-modal-window/div/div/app-add-car-modal/div[3]/button[2]"
edit_car_icon = "/html/body/app-root/app-global-layout/div/div/div/app-panel-layout/div/div/div/div[2]/div/app-garage/div/div[2]/div/ul/li/app-car/div/div[1]/div[2]/button[1]/span"
add_fuel_expense_per_car_button = "/html/body/app-root/app-global-layout/div/div/div/app-panel-layout/div/div/div/div[2]/div/app-garage/div/div[2]/div/ul/li/app-car/div/div[1]/div[2]/button[2]"
remove_car_button = "/html/body/ngb-modal-window/div/div/app-edit-car-modal/div[3]/button"
calendar_icon = "/html/body/ngb-modal-window/div/div/app-edit-car-modal/div[2]/app-edit-car-form/form/div[4]/div/div/button"
update_mileage_from_page_button = "/html/body/app-root/app-global-layout/div/div/div/app-panel-layout/div/div/div/div[2]/div/app-garage/div/div[2]/div/ul/li/app-car/div/div[2]/app-update-mileage-form/form/button"
car_select_dropdown = "//*[@id=\"carSelectDropdown\"]"
number_of_liters_input_field = "//*[@id=\"addExpenseLiters\"]"
total_cost_input_field = "//*[@id=\"addExpenseTotalCost\"]"

#CSS locators
home_header_menu_css = "nav > a"
about_header_menu_css = "nav > button:nth-child(2)"
contacts_header_menu_css = "nav > button:nth-child(3)"
sign_up_button_css = "div.col-12.col-lg-4 > div > button"
guest_log_in_link_css = "button.header-link.-guest"
sign_in_button_css = "button.btn.btn-outline-white"
support_link_css = "a.contacts_link.h4"
add_car_button_css = "div.panel-page_heading.d-flex.justify-content-between > button"
garage_header_menu_css = "a.btn.header-link.-active"
fuel_expenses_header_menu_css = "header > div > div > div > nav > a:nth-child(2)"
instructions_header_menu_css = "header > div > div > div > nav > a:nth-child(3)"
add_fuel_expense_button_css = "div.panel-page_heading.d-flex.flex-column.flex-lg-row > div > button"
close_add_car_popup_icon_css = "div.modal-header > button > span"
select_brand_dropdown_css = "#addCarBrand"
select_model_dropdown_css = "#addCarModel"
mileage_input_field_css = "#addCarMileage"
add_car_pop_up_cancel_button_css = "button.btn.btn-secondary"
add_car_pop_up_add_button_css = "div.modal-footer.d-flex.justify-content-end > button.btn.btn-primary"
edit_car_icon_css = "button.car_edit.btn.btn-edit"
add_fuel_expense_per_car_button_css = "button.car_add-expense.btn.btn-success"
remove_car_button_css = "div.modal-footer.d-flex.justify-content-between > button"
calendar_icon_css = "div:nth-child(4) > div > div > button"
update_mileage_from_page_button_css = "app-update-mileage-form > form > button"
car_select_dropdown_css = "#carSelectDropdown"
number_of_liters_input_field_css = "#addExpenseLiters"
total_cost_input_field_css = "#addExpenseTotalCost"
